// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3yvalfW0sM_8G_ohNP5KRFSuYNquTVpI',
    appId: '1:987265643272:android:c472dd297d5bc1ebfcf2bd',
    messagingSenderId: '987265643272',
    projectId: 'my-first-flutter-app-18460',
    storageBucket: 'my-first-flutter-app-18460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyButUXwtRunuiT7394DqRh1J8UpVK59qxg',
    appId: '1:987265643272:ios:d4a60a54df5e6f99fcf2bd',
    messagingSenderId: '987265643272',
    projectId: 'my-first-flutter-app-18460',
    storageBucket: 'my-first-flutter-app-18460.firebasestorage.app',
    androidClientId: '987265643272-crbocsm161fkvsoo0us8v8dt1u0d3ggg.apps.googleusercontent.com',
    iosClientId: '987265643272-r2plnpsk2s9ianm5b8mvkptt5fu6ko91.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

}